using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http.Features;
using System.IO.Compression;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.RateLimiting;
using Konscious.Security.Cryptography;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.Data.Sqlite;

var dataRoot=Environment.GetEnvironmentVariable("SONAR_DATA_ROOT")??"/data";
var experimentRoot=Path.Combine(dataRoot,"experiments"); var resultRoot=Path.Combine(dataRoot,"results"); var configRoot=Path.Combine(dataRoot,"config");
Directory.CreateDirectory(experimentRoot);Directory.CreateDirectory(resultRoot);Directory.CreateDirectory(configRoot);
var authFile=Path.Combine(configRoot,"auth.json"); var dbFile=Path.Combine(configRoot,"sonar.db"); var externalStudiesFile=Path.Combine(configRoot,"external-studies.json");
const string CsvHeader="Time,TotalElapsedTime,ExpElapsedTime,Phase,PhaseElapsedTimeSec,EventType,Signal_Type,Signal_ID,Signal_Bearing,Signal_Width,Signal_Alpha,BTH_SelectedSignals,BTH_SelectedBearing,Class_Selected,Class_Types,Class_Correct,Class_Confidence,Class_Feedback,Alert_Type,Alert_Text,Alert_Bearing,Alert_SignalId,RunId";

if(args.Length>0 && (args[0]=="reset-password"||args[0]=="init-password")){
 Console.Write("New operator password: ");var p=ReadPassword();Console.WriteLine();if(p.Length<12){Console.Error.WriteLine("Password must be at least 12 characters.");return;}await AuthStore.Save(authFile,p);Console.WriteLine("Operator password updated. Existing elevated settings tokens are invalidated.");return;
}
await Db.Init(dbFile);
var builder=WebApplication.CreateBuilder(args);
// Infrastructure limits are slightly larger than the application-level 64 MiB ZIP limit
// so the upload endpoint can return a useful JSON error instead of Kestrel rejecting it first.
const long MaxExperimentZipBytes = 64L * 1024 * 1024;
const long MaxMultipartBodyBytes = 70L * 1024 * 1024;
builder.WebHost.ConfigureKestrel(o => o.Limits.MaxRequestBodySize = 72L * 1024 * 1024);
builder.Services.Configure<FormOptions>(o => o.MultipartBodyLengthLimit = MaxMultipartBodyBytes);
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(o=>{o.Cookie.Name="sonar_session";o.Cookie.HttpOnly=true;o.Cookie.SameSite=SameSiteMode.Strict;o.Cookie.SecurePolicy=CookieSecurePolicy.Always;o.SlidingExpiration=true;o.ExpireTimeSpan=TimeSpan.FromHours(12);o.Events.OnRedirectToLogin=c=>{c.Response.StatusCode=401;return Task.CompletedTask;};o.Events.OnRedirectToAccessDenied=c=>{c.Response.StatusCode=403;return Task.CompletedTask;};});
builder.Services.AddAuthorization();
builder.Services.AddRateLimiter(o=>o.AddFixedWindowLimiter("login",x=>{x.PermitLimit=8;x.Window=TimeSpan.FromMinutes(5);x.QueueLimit=0;x.QueueProcessingOrder=QueueProcessingOrder.OldestFirst;}));
var app=builder.Build();app.UseRateLimiter();app.UseAuthentication();app.UseAuthorization();

app.MapGet("/health",()=>Results.Ok(new{ok=true}));
app.MapPost("/auth/login",async(HttpContext c,PasswordRequest r)=>{if(!await AuthStore.Verify(authFile,r.password))return Results.Json(new{ok=false,message="Invalid password."},statusCode:401);var claims=new[]{new Claim(ClaimTypes.Name,"operator"),new Claim(ClaimTypes.Role,"operator")};await c.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,new ClaimsPrincipal(new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme)));return Results.Ok(new{ok=true,message="Signed in."});}).RequireRateLimiting("login");
app.MapPost("/auth/reauth",async(HttpContext c,PasswordRequest r)=>{if(c.User.Identity?.IsAuthenticated != true)return Results.Unauthorized();if(!await AuthStore.Verify(authFile,r.password))return Results.Json(new{ok=false,message="Invalid password."},statusCode:401);var a=await AuthStore.Load(authFile);c.Response.Cookies.Append("sonar_admin",a.AdminKey,new CookieOptions{HttpOnly=true,Secure=true,SameSite=SameSiteMode.Strict,Expires=DateTimeOffset.UtcNow.AddMinutes(15)});return Results.Ok(new{ok=true,message="Settings unlocked for 15 minutes."});}).RequireAuthorization();
app.MapPost("/auth/change-password",async(HttpContext c,ChangePasswordRequest r)=>{if(!Admin(c,authFile)||!await AuthStore.Verify(authFile,r.currentPassword))return Results.Json(new{ok=false,message="Re-authentication required."},statusCode:401);if((r.newPassword??"").Length<12)return Results.BadRequest(new{ok=false,message="New password must be at least 12 characters."});await AuthStore.Save(authFile,r.newPassword);c.Response.Cookies.Delete("sonar_admin");return Results.Ok(new{ok=true,message="Password changed. Re-open Settings to authenticate again."});}).RequireAuthorization();


app.MapPost("/external/launch",async(HttpContext c,ExternalLaunchRequest r)=>{
 var provider=NormalizeProvider(r.provider);if(provider is null)return Results.BadRequest(new{ok=false,message="Unknown external study provider."});
 var participant=(r.participantId??"").Trim();var study=(r.providerStudyId??"").Trim();if(participant.Length==0||study.Length==0)return Results.BadRequest(new{ok=false,message="Participant ID and provider study/project ID are required."});
 var mappings=await ExternalStudyStore.Load(externalStudiesFile);var map=mappings.FirstOrDefault(x=>x.Enabled&&NormalizeProvider(x.Provider)==provider&&string.Equals(x.ProviderStudyId,study,StringComparison.OrdinalIgnoreCase));
 if(map is null)return Results.Json(new{ok=false,message="No enabled SONAR external-study mapping matches this provider study/project ID."},statusCode:404);
 var experimentDir=SafePackageDir(experimentRoot,map.ExperimentPackage);if(!File.Exists(Path.Combine(experimentDir,"experiment.json")))return Results.Json(new{ok=false,message="The mapped SONAR experiment package is not installed."},statusCode:409);
 c.Response.Cookies.Delete("sonar_admin");
 var claims=new[]{new Claim(ClaimTypes.Name,"external:"+provider+":"+participant),new Claim(ClaimTypes.Role,"participant"),new Claim("sonar_external","1"),new Claim("sonar_subject",participant),new Claim("sonar_experiment",map.ExperimentPackage),new Claim("sonar_provider",provider),new Claim("sonar_provider_study",study),new Claim("sonar_provider_session",r.sessionId??""),new Claim("sonar_provider_assignment",r.assignmentId??"")};
 await c.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,new ClaimsPrincipal(new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme)),new AuthenticationProperties{IsPersistent=false,ExpiresUtc=DateTimeOffset.UtcNow.AddHours(12)});
 return Results.Ok(new{ok=true,message="External study launch accepted.",provider,participantId=participant,providerStudyId=study,sessionId=r.sessionId??"",assignmentId=r.assignmentId??"",experimentPackage=map.ExperimentPackage,completionUrl=map.CompletionUrl??"",autoStart=map.AutoStart,showInstructions=map.ShowInstructions});
});

app.MapGet("/experiments",(HttpContext c)=>Results.Ok(ExperimentFiles.List(experimentRoot,AssignedExperiment(c)))).RequireAuthorization();
app.MapGet("/experiments/{package}/definition",(HttpContext c,string package)=>{if(!ExperimentAllowed(c,package))return Results.Forbid();var f=SafeExperimentFile(experimentRoot,package,"experiment.json");return File.Exists(f)?Results.File(f,"application/json"):Results.NotFound();}).RequireAuthorization();
app.MapGet("/experiments/{package}/assets/{**asset}",(HttpContext c,string package,string asset)=>{if(!ExperimentAllowed(c,package))return Results.Forbid();var f=SafeExperimentFile(experimentRoot,package,asset);return File.Exists(f)?Results.File(f,ContentType(f)):Results.NotFound();}).RequireAuthorization();
app.MapGet("/results/completed",async(HttpContext c,string subject,string experiment)=>{if(!SubjectExperimentAllowed(c,subject,experiment))return Results.Forbid();return Results.Ok(new{completed=await Db.HasCompleted(dbFile,subject,experiment)});}).RequireAuthorization();

app.MapPost("/results/runs",async(HttpContext c,RunStartRequest start)=>{var m=start.metadata;if(IsExternal(c)){var subject=c.User.FindFirst("sonar_subject")?.Value??"";var exp=c.User.FindFirst("sonar_experiment")?.Value??"";if(!string.Equals(m.SubjectId,subject,StringComparison.Ordinal)||!string.Equals(m.ExperimentPackage,exp,StringComparison.Ordinal))return Results.Forbid();m=m with { SubjectId=subject,ExperimentPackage=exp,OperatorId="External:"+(c.User.FindFirst("sonar_provider")?.Value??"external"),Location="Web",LaunchMode="External",RecruitmentProvider=c.User.FindFirst("sonar_provider")?.Value??"",ProviderParticipantId=subject,ProviderStudyId=c.User.FindFirst("sonar_provider_study")?.Value??"",ProviderSessionId=c.User.FindFirst("sonar_provider_session")?.Value??"",ProviderAssignmentId=c.User.FindFirst("sonar_provider_assignment")?.Value??"" };}if(string.IsNullOrWhiteSpace(m.RunId))return Results.BadRequest("RunId is required.");var hash=Sha256Text(start.definitionJson??"");if(!string.Equals(hash,m.ExperimentDefinitionHash,StringComparison.OrdinalIgnoreCase))return Results.BadRequest("ExperimentDefinitionHash does not match submitted experiment snapshot.");try{using var parsed=JsonDocument.Parse(start.definitionJson);if(!parsed.RootElement.TryGetProperty("Name",out var en)||en.GetString()!=m.ExperimentName)return Results.BadRequest("Experiment snapshot name does not match metadata.");}catch(Exception e){return Results.BadRequest("Invalid experiment snapshot: "+e.Message);}var stem=Safe(m.SubjectId)+"__"+Safe(m.ExperimentPackage)+"__"+DateTime.UtcNow.ToString("yyyyMMddTHHmmssfffZ")+"__"+m.RunId[..Math.Min(8,m.RunId.Length)];var csv=Path.Combine(resultRoot,stem+".csv");var meta=Path.Combine(resultRoot,stem+".meta.json");var snap=Path.Combine(resultRoot,stem+".experiment.json");await File.WriteAllTextAsync(csv,CsvHeader+Environment.NewLine,new UTF8Encoding(false));m=m with { Completed=false, TerminationReason="Active" };await File.WriteAllTextAsync(meta,JsonSerializer.Serialize(m,new JsonSerializerOptions{WriteIndented=true}));await File.WriteAllTextAsync(snap,start.definitionJson??"",new UTF8Encoding(false));await Db.Start(dbFile,m,Path.GetFileName(csv),Path.GetFileName(meta));return Results.Ok(new{ok=true});}).RequireAuthorization();
app.MapPost("/results/runs/{runId}/heartbeat",async(string runId)=>{await Db.Heartbeat(dbFile,runId);return Results.Ok();}).RequireAuthorization();
app.MapPost("/results/runs/{runId}/events",async(string runId,EventEnvelope env)=>{var row=await Db.GetRun(dbFile,runId);if(row is null)return Results.NotFound();if(await Db.SequenceExists(dbFile,runId,env.sequence))return Results.Ok(new{duplicate=true});var path=Path.Combine(resultRoot,row.Value.csv);await File.AppendAllTextAsync(path,ToCsv(env.@event,runId)+Environment.NewLine,new UTF8Encoding(false));await Db.AddSequence(dbFile,runId,env.sequence);return Results.Ok();}).RequireAuthorization();
app.MapPost("/results/runs/{runId}/finish",async(string runId,FinishRequest f)=>{var row=await Db.GetRun(dbFile,runId);if(row is null)return Results.NotFound();await Db.Finish(dbFile,runId,f.completed,f.terminationReason,f.endedUtc);await RewriteMeta(Path.Combine(resultRoot,row.Value.meta),f.completed,f.terminationReason,f.endedUtc);return Results.Ok();}).RequireAuthorization();

app.MapGet("/admin/experiments",(HttpContext c)=>Admin(c,authFile)?Results.Ok(ExperimentFiles.List(experimentRoot)):Results.Unauthorized()).RequireAuthorization();
app.MapMethods("/admin/experiments/storage-status", new[] { "GET", "POST" }, (HttpContext c)=>{if(!Admin(c,authFile))return Results.Unauthorized();try{Directory.CreateDirectory(experimentRoot);var test=Path.Combine(experimentRoot,".sonar-write-test-"+Guid.NewGuid().ToString("N"));File.WriteAllText(test,"ok");File.Delete(test);return Results.Ok(new{writable=true,message="Experiment storage is writable."});}catch(Exception e){return Results.Ok(new{writable=false,message=e.Message});}}).RequireAuthorization();
app.MapPost("/admin/experiments/upload",async(HttpContext c,IFormFile file)=>{if(!Admin(c,authFile))return Results.Json(new{ok=false,message="Settings authorization expired. Re-enter the operator password and try again."},statusCode:401);try{if(file.Length<=0)return Results.BadRequest(new{ok=false,message="The selected ZIP is empty."});if(file.Length>MaxExperimentZipBytes)return Results.Json(new{ok=false,message="ZIP exceeds the 64 MiB experiment upload limit."},statusCode:413);await using var ms=new MemoryStream();await file.CopyToAsync(ms);await InstallZip(ms.ToArray(),file.FileName,experimentRoot);return Results.Ok(new{ok=true,message="Experiment uploaded."});}catch(UnauthorizedAccessException e){return Results.Json(new{ok=false,message="The server cannot write to the Experiments directory. Check the Deploy/Experiments bind-mount permissions. "+e.Message},statusCode:500);}catch(IOException e){return Results.Json(new{ok=false,message="Experiment storage I/O error: "+e.Message},statusCode:500);}catch(Exception e){return Results.BadRequest(new{ok=false,message=e.Message});}}).DisableAntiforgery().RequireAuthorization();
app.MapPost("/admin/experiments/upload-base64",async(HttpContext c,UploadBase64 u)=>{if(!Admin(c,authFile))return Results.Unauthorized();try{var bytes=Convert.FromBase64String(u.base64);await InstallZip(bytes,u.fileName,experimentRoot);return Results.Ok(new{ok=true});}catch(Exception e){return Results.BadRequest(new{ok=false,message=e.Message});}}).RequireAuthorization();
app.MapDelete("/admin/experiments/{package}",(HttpContext c,string package)=>{if(!Admin(c,authFile))return Results.Unauthorized();var dir=SafePackageDir(experimentRoot,package);if(!Directory.Exists(dir))return Results.NotFound();Directory.Delete(dir,true);return Results.Ok(new{ok=true});}).RequireAuthorization();
app.MapGet("/admin/results",async(HttpContext c,string? filter)=>Admin(c,authFile)?Results.Ok(await Db.Results(dbFile,filter??"")):Results.Unauthorized()).RequireAuthorization();
app.MapGet("/admin/results/file/{fileName}",(HttpContext c,string fileName)=>{if(!Admin(c,authFile))return Results.Unauthorized();var f=SafeResultFile(resultRoot,fileName);return File.Exists(f)?Results.File(f,"application/octet-stream",Path.GetFileName(f)):Results.NotFound();}).RequireAuthorization();
app.MapGet("/admin/results/download",(HttpContext c,string? filter)=>{if(!Admin(c,authFile))return Results.Unauthorized();var files=Directory.GetFiles(resultRoot).Where(f=>Path.GetFileName(f).Contains(filter??"",StringComparison.OrdinalIgnoreCase)).ToArray();return ZipFiles(files,"sonar-results.zip");}).RequireAuthorization();
var tokens=new Dictionary<string,(DateTime expires,string[] files)>();
app.MapPost("/admin/results/download-selected",(HttpContext c,SelectedFiles s)=>{if(!Admin(c,authFile))return Results.Unauthorized();var fs=s.files.SelectMany(x=>{var safe=SafeResultFile(resultRoot,x);var stem=Path.Combine(resultRoot,Path.GetFileNameWithoutExtension(safe));return new[]{safe,stem+".meta.json",stem+".experiment.json"};}).Where(File.Exists).Distinct().ToArray();var token=Guid.NewGuid().ToString("N");lock(tokens)tokens[token]=(DateTime.UtcNow.AddMinutes(2),fs);return Results.Json(token);}).RequireAuthorization();
app.MapGet("/admin/results/download-token/{token}",(HttpContext c,string token)=>{if(!Admin(c,authFile))return Results.Unauthorized();(DateTime expires,string[] files) t;lock(tokens){if(!tokens.TryGetValue(token,out t)||t.expires<DateTime.UtcNow)return Results.NotFound();tokens.Remove(token);}return ZipFiles(t.files,"sonar-selected-results.zip");}).RequireAuthorization();

app.MapGet("/admin/external-studies",async(HttpContext c)=>Admin(c,authFile)?Results.Ok(await ExternalStudyStore.Load(externalStudiesFile)):Results.Unauthorized()).RequireAuthorization();
app.MapPost("/admin/external-studies",async(HttpContext c,ExternalStudyConfig input)=>{
 if(!Admin(c,authFile))return Results.Unauthorized();var provider=NormalizeProvider(input.Provider);if(provider is null)return Results.BadRequest(new{ok=false,message="Provider must be Prolific, Connect, SONA, or Generic."});
 var study=(input.ProviderStudyId??"").Trim();var experiment=(input.ExperimentPackage??"").Trim();if(study.Length==0)return Results.BadRequest(new{ok=false,message="Provider Study / Project ID is required."});if(experiment.Length==0||!File.Exists(Path.Combine(SafePackageDir(experimentRoot,experiment),"experiment.json")))return Results.BadRequest(new{ok=false,message="Select an installed SONAR experiment package."});
 var completion=(input.CompletionUrl??"").Trim();if(completion.Length>0&&(!Uri.TryCreate(completion,UriKind.Absolute,out var cu)||(cu.Scheme!="https"&&cu.Scheme!="http")))return Results.BadRequest(new{ok=false,message="Completion URL must be an absolute http/https URL."});
 var all=await ExternalStudyStore.Load(externalStudiesFile);var id=string.IsNullOrWhiteSpace(input.Id)?Guid.NewGuid().ToString("N"):input.Id.Trim();if(all.Any(x=>x.Id!=id&&NormalizeProvider(x.Provider)==provider&&string.Equals(x.ProviderStudyId,study,StringComparison.OrdinalIgnoreCase)))return Results.Conflict(new{ok=false,message="That provider study/project ID already has a SONAR mapping."});
 var item=new ExternalStudyConfig(id,provider,study,experiment,input.AutoStart,input.ShowInstructions,completion,input.Enabled);var ix=all.FindIndex(x=>x.Id==id);if(ix>=0)all[ix]=item;else all.Add(item);await ExternalStudyStore.Save(externalStudiesFile,all);return Results.Ok(item);
}).RequireAuthorization();
app.MapDelete("/admin/external-studies/{id}",async(HttpContext c,string id)=>{if(!Admin(c,authFile))return Results.Unauthorized();var all=await ExternalStudyStore.Load(externalStudiesFile);var removed=all.RemoveAll(x=>x.Id==id);if(removed==0)return Results.NotFound();await ExternalStudyStore.Save(externalStudiesFile,all);return Results.Ok(new{ok=true});}).RequireAuthorization();

app.Lifetime.ApplicationStarted.Register(()=>_ = Task.Run(async()=>{while(!app.Lifetime.ApplicationStopping.IsCancellationRequested){try{await Task.Delay(TimeSpan.FromSeconds(30),app.Lifetime.ApplicationStopping);var stale=await Db.MarkStale(dbFile,TimeSpan.FromSeconds(75));foreach(var x in stale)await RewriteMeta(Path.Combine(resultRoot,x),false,"BrowserDisconnected",DateTime.UtcNow.ToString("O"));}catch(OperationCanceledException){break;}catch(Exception e){Console.Error.WriteLine("Run reaper: "+e.Message);}}}));
app.Run();

static bool IsExternal(HttpContext c)=>string.Equals(c.User.FindFirst("sonar_external")?.Value,"1",StringComparison.Ordinal);
static string? AssignedExperiment(HttpContext c)=>IsExternal(c)?c.User.FindFirst("sonar_experiment")?.Value:null;
static bool ExperimentAllowed(HttpContext c,string package){var assigned=AssignedExperiment(c);return string.IsNullOrWhiteSpace(assigned)||string.Equals(assigned,package,StringComparison.Ordinal);}
static bool SubjectExperimentAllowed(HttpContext c,string subject,string experiment){if(!IsExternal(c))return true;return string.Equals(c.User.FindFirst("sonar_subject")?.Value,subject,StringComparison.Ordinal)&&string.Equals(c.User.FindFirst("sonar_experiment")?.Value,experiment,StringComparison.Ordinal);}
static string? NormalizeProvider(string? p)=>(p??"").Trim().ToLowerInvariant() switch{"prolific"=>"prolific","connect" or "cloudresearch" or "cloudresearchconnect"=>"connect","sona"=>"sona","generic"=>"generic",_=>null};
static bool Admin(HttpContext c,string authFile){if(!c.Request.Cookies.TryGetValue("sonar_admin",out var token))return false;try{return CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(token),Encoding.UTF8.GetBytes(AuthStore.Load(authFile).GetAwaiter().GetResult().AdminKey));}catch{return false;}}
static string Safe(string s){var bad=Path.GetInvalidFileNameChars();return new string((s??"unknown").Select(c=>bad.Contains(c)?'_':c).ToArray());}
static string SafePackageDir(string root,string package){if(package.IndexOfAny(Path.GetInvalidFileNameChars())>=0||package.Contains(".."))throw new InvalidOperationException("Invalid package name.");var p=Path.GetFullPath(Path.Combine(root,package));if(!p.StartsWith(Path.GetFullPath(root)+Path.DirectorySeparatorChar,StringComparison.Ordinal))throw new InvalidOperationException("Invalid path.");return p;}
static string SafeExperimentFile(string root,string package,string rel){var dir=SafePackageDir(root,package);var p=Path.GetFullPath(Path.Combine(dir,rel??""));if(!p.StartsWith(dir+Path.DirectorySeparatorChar,StringComparison.Ordinal)&&p!=dir)throw new InvalidOperationException("Asset path escapes package.");return p;}
static string SafeResultFile(string root,string name){name=Path.GetFileName(name);return Path.Combine(root,name);}
static string ContentType(string f)=>Path.GetExtension(f).ToLowerInvariant() switch{".json"=>"application/json",".md"=>"text/markdown; charset=utf-8",".png"=>"image/png",".jpg" or ".jpeg"=>"image/jpeg",".wav"=>"audio/wav",".mp3"=>"audio/mpeg",_=>"application/octet-stream"};
static IResult ZipFiles(string[] files,string download){var ms=new MemoryStream();using(var zip=new ZipArchive(ms,ZipArchiveMode.Create,true)){foreach(var f in files){var e=zip.CreateEntry(Path.GetFileName(f),CompressionLevel.Fastest);using var dst=e.Open();using var src=File.OpenRead(f);src.CopyTo(dst);}}ms.Position=0;return Results.File(ms,"application/zip",download);}
static async Task InstallZip(byte[] data,string original,string root){
 if(data.Length>64*1024*1024)throw new InvalidOperationException("ZIP exceeds 64 MB upload limit.");
 var tmp=Path.Combine(Path.GetTempPath(),"sonar-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(tmp);
 try{
  using var ms=new MemoryStream(data);using var z=new ZipArchive(ms,ZipArchiveMode.Read);long expanded=0;int count=0;
  foreach(var e in z.Entries){if(++count>2000)throw new InvalidOperationException("ZIP contains too many files.");expanded+=e.Length;if(expanded>256L*1024*1024)throw new InvalidOperationException("Expanded ZIP exceeds 256 MB.");if(string.IsNullOrEmpty(e.Name))continue;var target=Path.GetFullPath(Path.Combine(tmp,e.FullName));if(!target.StartsWith(Path.GetFullPath(tmp)+Path.DirectorySeparatorChar,StringComparison.Ordinal))throw new InvalidOperationException("ZIP contains an unsafe path.");Directory.CreateDirectory(Path.GetDirectoryName(target)!);await using var dst=File.Create(target);await using var src=e.Open();await src.CopyToAsync(dst);}
  var jsons=Directory.GetFiles(tmp,"experiment.json",SearchOption.AllDirectories);if(jsons.Length!=1)throw new InvalidOperationException("ZIP must contain exactly one experiment.json.");var packageDir=Path.GetDirectoryName(jsons[0])!;if(Path.GetFullPath(packageDir)==Path.GetFullPath(tmp))throw new InvalidOperationException("ZIP must contain one top-level experiment package directory.");var package=Path.GetFileName(packageDir);
  using var doc=JsonDocument.Parse(await File.ReadAllTextAsync(jsons[0]));var errors=ExperimentFiles.ValidatePackage(doc.RootElement,packageDir);if(errors.Count>0)throw new InvalidOperationException("Experiment validation failed:\n - "+string.Join("\n - ",errors));
  var final=SafePackageDir(root,package);
  // The extraction directory is normally /tmp while root may be a Docker bind mount.
  // Directory.Move cannot cross Linux filesystem/mount boundaries (EXDEV), so copy
  // the validated package into a staging area on the destination filesystem first.
  var stagingBase=Path.Combine(root,".staging",Guid.NewGuid().ToString("N"));
  var incoming=Path.Combine(stagingBase,"incoming");
  var backup=Path.Combine(stagingBase,"backup");
  Directory.CreateDirectory(stagingBase);
  var backedUp=false;var installed=false;
  try{
   await CopyDirectoryAsync(packageDir,incoming);
   if(Directory.Exists(final)){Directory.Move(final,backup);backedUp=true;}
   Directory.Move(incoming,final);installed=true;
   if(backedUp)TryDeleteDirectory(backup);
  }catch{
   if(!installed&&backedUp&&!Directory.Exists(final)&&Directory.Exists(backup))Directory.Move(backup,final);
   throw;
  }finally{
   TryDeleteDirectory(incoming);
   if(installed)TryDeleteDirectory(backup);
   TryDeleteDirectory(stagingBase);
   var stagingRoot=Path.Combine(root,".staging");
   try{if(Directory.Exists(stagingRoot)&&!Directory.EnumerateFileSystemEntries(stagingRoot).Any())Directory.Delete(stagingRoot);}catch{}
  }
 }finally{if(Directory.Exists(tmp))Directory.Delete(tmp,true);}
}
static void TryDeleteDirectory(string path){try{if(Directory.Exists(path))Directory.Delete(path,true);}catch{}}
static async Task CopyDirectoryAsync(string source,string destination){
 Directory.CreateDirectory(destination);
 foreach(var dir in Directory.GetDirectories(source,"*",SearchOption.AllDirectories)){
  var rel=Path.GetRelativePath(source,dir);Directory.CreateDirectory(Path.Combine(destination,rel));
 }
 foreach(var file in Directory.GetFiles(source,"*",SearchOption.AllDirectories)){
  var rel=Path.GetRelativePath(source,file);var target=Path.Combine(destination,rel);Directory.CreateDirectory(Path.GetDirectoryName(target)!);
  await using var src=new FileStream(file,FileMode.Open,FileAccess.Read,FileShare.Read,81920,true);
  await using var dst=new FileStream(target,FileMode.CreateNew,FileAccess.Write,FileShare.None,81920,true);
  await src.CopyToAsync(dst);
 }
}
static async Task RewriteMeta(string path,bool completed,string reason,string ended){if(!File.Exists(path))return;using var d=JsonDocument.Parse(await File.ReadAllTextAsync(path));var map=JsonSerializer.Deserialize<Dictionary<string,object?>>(d.RootElement.GetRawText())??new();map["Completed"]=completed;map["TerminationReason"]=reason;map["EndedUtc"]=ended;await File.WriteAllTextAsync(path,JsonSerializer.Serialize(map,new JsonSerializerOptions{WriteIndented=true}));}
static string ToCsv(ResultEventDto e,string run)=>string.Join(",",new[]{e.TimeUtc,F(e.TotalElapsedTimeSec),F(e.ExpElapsedTimeSec),e.Phase,F(e.PhaseElapsedTimeSec),e.EventType,e.Signal_Type,e.Signal_ID,e.Signal_Bearing,e.Signal_Width,e.Signal_Alpha,e.BTH_SelectedSignals,e.BTH_SelectedBearing,e.Class_Selected,e.Class_Types,e.Class_Correct,e.Class_Confidence,e.Class_Feedback,e.Alert_Type,e.Alert_Text,e.Alert_Bearing,e.Alert_SignalId,run}.Select(Csv));
static string F(float f)=>f.ToString("0.000",System.Globalization.CultureInfo.InvariantCulture);static string Csv(string? s){s??="";return s.IndexOfAny([',','\"','\n','\r'])>=0?"\""+s.Replace("\"","\"\"")+"\"":s;}
static string Sha256Text(string text){var b=SHA256.HashData(Encoding.UTF8.GetBytes(text??""));return Convert.ToHexString(b).ToLowerInvariant();}
static string ReadPassword(){var b=new StringBuilder();ConsoleKeyInfo k;while((k=Console.ReadKey(true)).Key!=ConsoleKey.Enter){if(k.Key==ConsoleKey.Backspace&&b.Length>0)b.Length--;else if(!char.IsControl(k.KeyChar))b.Append(k.KeyChar);}return b.ToString();}
record PasswordRequest(string password); record ExternalLaunchRequest(string provider,string participantId,string providerStudyId,string sessionId,string assignmentId); record ExternalStudyConfig(string Id,string Provider,string ProviderStudyId,string ExperimentPackage,bool AutoStart,bool ShowInstructions,string CompletionUrl,bool Enabled); record RunStartRequest(RunMetadata metadata,string definitionJson); record ChangePasswordRequest(string currentPassword,string newPassword); record UploadBase64(string fileName,string base64); record SelectedFiles(string[] files); record FinishRequest(bool completed,string terminationReason,string endedUtc); record EventEnvelope(long sequence,ResultEventDto @event);
record ResultEventDto(string TimeUtc,float TotalElapsedTimeSec,float ExpElapsedTimeSec,float PhaseElapsedTimeSec,string Phase,string EventType,string Signal_Type,string Signal_ID,string Signal_Bearing,string Signal_Width,string Signal_Alpha,string BTH_SelectedSignals,string BTH_SelectedBearing,string Class_Selected,string Class_Types,string Class_Correct,string Class_Confidence,string Class_Feedback,string Alert_Type,string Alert_Text,string Alert_Bearing,string Alert_SignalId,string RunId);
record RunMetadata(int ResultSchemaVersion,string RunId,string SubjectId,string OperatorId,string Location,string ExperimentPackage,string ExperimentName,string ExperimentVersion,string ExperimentDefinitionHash,string ApplicationVersion,string Platform,string StartedUtc,string EndedUtc,string TerminationReason,string WaterfallPalette,long RandomizationSeed,bool Completed,string LaunchMode,string RecruitmentProvider,string ProviderParticipantId,string ProviderStudyId,string ProviderSessionId,string ProviderAssignmentId);
record AuthData(string Salt,string Hash,string AdminKey,int MemoryKb,int Iterations,int Parallelism);

static class ExternalStudyStore {
 static readonly SemaphoreSlim Gate=new(1,1);
 public static async Task<List<ExternalStudyConfig>> Load(string f){await Gate.WaitAsync();try{return await LoadUnlocked(f);}finally{Gate.Release();}}
 public static async Task Save(string f,List<ExternalStudyConfig> items){await Gate.WaitAsync();try{Directory.CreateDirectory(Path.GetDirectoryName(f)!);var tmp=f+".tmp";await File.WriteAllTextAsync(tmp,JsonSerializer.Serialize(items,new JsonSerializerOptions{WriteIndented=true}));File.Move(tmp,f,true);}finally{Gate.Release();}}
 static async Task<List<ExternalStudyConfig>> LoadUnlocked(string f){if(!File.Exists(f))return new();try{return JsonSerializer.Deserialize<List<ExternalStudyConfig>>(await File.ReadAllTextAsync(f),new JsonSerializerOptions{PropertyNameCaseInsensitive=true})??new();}catch{return new();}}
}
static class AuthStore {
 public static async Task<AuthData> Load(string f){if(!File.Exists(f))throw new InvalidOperationException("Operator password has not been initialized. Run: docker compose run --rm api init-password");return JsonSerializer.Deserialize<AuthData>(await File.ReadAllTextAsync(f))!;}
 public static async Task Save(string f,string password){var salt=RandomNumberGenerator.GetBytes(16);const int mem=65536,it=4,par=2;var hash=await Hash(password,salt,mem,it,par);var a=new AuthData(Convert.ToBase64String(salt),Convert.ToBase64String(hash),Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)),mem,it,par);await File.WriteAllTextAsync(f,JsonSerializer.Serialize(a,new JsonSerializerOptions{WriteIndented=true}));}
 public static async Task<bool> Verify(string f,string p){if(!File.Exists(f))return false;var a=await Load(f);var got=await Hash(p,Convert.FromBase64String(a.Salt),a.MemoryKb,a.Iterations,a.Parallelism);return CryptographicOperations.FixedTimeEquals(got,Convert.FromBase64String(a.Hash));}
 static Task<byte[]> Hash(string p,byte[] salt,int mem,int it,int par){var a=new Argon2id(Encoding.UTF8.GetBytes(p)){Salt=salt,MemorySize=mem,Iterations=it,DegreeOfParallelism=par};return Task.FromResult(a.GetBytes(32));}
}
static class ExperimentFiles {
 public static object[] List(string root,string? onlyPackage=null)=>Directory.GetDirectories(root).Where(d=>string.IsNullOrWhiteSpace(onlyPackage)||string.Equals(Path.GetFileName(d),onlyPackage,StringComparison.Ordinal)).Select(d=>{var f=Path.Combine(d,"experiment.json");if(!File.Exists(f))return null;try{using var j=JsonDocument.Parse(File.ReadAllText(f));var r=j.RootElement;return (object)new{packageName=Path.GetFileName(d),name=r.TryGetProperty("Name",out var n)?n.GetString():Path.GetFileName(d),version=r.TryGetProperty("Version",out var v)?v.GetString():""};}catch{return null;}}).Where(x=>x!=null).ToArray()!;
 public static List<string> ValidatePackage(JsonElement root,string packageDir){
  var e=new List<string>();if(root.ValueKind!=JsonValueKind.Object){e.Add("Root must be an object.");return e;}if(!root.TryGetProperty("SchemaVersion",out var sv)||sv.ValueKind!=JsonValueKind.Number||sv.GetInt32()!=1)e.Add("SchemaVersion must be 1.");if(!Text(root,"Name",out _))e.Add("Name is required.");if(!Text(root,"Version",out _))e.Add("Version is required.");
  string instructions=root.TryGetProperty("InstructionsFile",out var ins)&&ins.ValueKind==JsonValueKind.String?ins.GetString()!:"instructions.md";CheckAsset(packageDir,instructions,"InstructionsFile",e);
  if(!root.TryGetProperty("ExperimentSettings",out var set)||set.ValueKind!=JsonValueKind.Object){e.Add("ExperimentSettings is required.");return e;}if(!set.TryGetProperty("RandomizationSeed",out var seed)||seed.ValueKind!=JsonValueKind.Number||!seed.TryGetInt64(out var seedVal)||seedVal==0)e.Add("RandomizationSeed must be a non-zero integer.");if(set.TryGetProperty("ShowResultsAtEnd",out var showResults)&&(showResults.ValueKind!=JsonValueKind.String||(showResults.GetString()!="Yes"&&showResults.GetString()!="No")))e.Add("ShowResultsAtEnd must be 'Yes' or 'No'.");if(set.TryGetProperty("HideLofarSignalsIfNoSelectedBTH",out var hideLofar)&&(hideLofar.ValueKind!=JsonValueKind.String||(hideLofar.GetString()!="Yes"&&hideLofar.GetString()!="No")))e.Add("HideLofarSignalsIfNoSelectedBTH must be 'Yes' or 'No'.");
  var defaultSignals=new HashSet<string>(StringComparer.Ordinal);if(set.TryGetProperty("SignalDefinitions",out var defs)&&defs.ValueKind==JsonValueKind.Object){foreach(var d in defs.EnumerateObject()){defaultSignals.Add(d.Name);if(d.Value.TryGetProperty("AudioFile",out var a)&&a.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(a.GetString()))CheckAsset(packageDir,a.GetString()!,"SignalDefinitions."+d.Name+".AudioFile",e);}}else e.Add("ExperimentSettings.SignalDefinitions is required.");
  if(set.TryGetProperty("BackgroundAudio",out var ba)&&ba.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(ba.GetString()))CheckAsset(packageDir,ba.GetString()!,"BackgroundAudio",e);float defaultDur=Number(set,"SignalDurationSec",30);if(defaultDur<=0)e.Add("SignalDurationSec must be > 0.");
  if(!set.TryGetProperty("PhaseOrder",out var po)||po.ValueKind!=JsonValueKind.Array||po.GetArrayLength()==0){e.Add("PhaseOrder must contain at least one phase.");return e;}if(!root.TryGetProperty("Phases",out var phases)||phases.ValueKind!=JsonValueKind.Object){e.Add("Phases is required.");return e;}
  foreach(var pn in po.EnumerateArray()){if(pn.ValueKind!=JsonValueKind.String)continue;string name=pn.GetString()!;if(!phases.TryGetProperty(name,out var phase)||phase.ValueKind!=JsonValueKind.Object){e.Add($"PhaseOrder references missing phase '{name}'.");continue;}if(phase.TryGetProperty("HideLofarSignalsIfNoSelectedBTH",out var phaseHideLofar)&&(phaseHideLofar.ValueKind!=JsonValueKind.String||(phaseHideLofar.GetString()!="Yes"&&phaseHideLofar.GetString()!="No")))e.Add($"Phase '{name}' HideLofarSignalsIfNoSelectedBTH must be 'Yes' or 'No'.");var available=new HashSet<string>(defaultSignals,StringComparer.Ordinal);if(phase.TryGetProperty("SignalDefinitions",out var ovs)&&ovs.ValueKind==JsonValueKind.Array)foreach(var ov in ovs.EnumerateArray())if(Text(ov,"Name",out var on)){available.Add(on);if(ov.TryGetProperty("AudioFile",out var oa)&&oa.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(oa.GetString()))CheckAsset(packageDir,oa.GetString()!,$"Phase {name} signal {on} AudioFile",e);}
   if(phase.TryGetProperty("BackgroundAudio",out var pba)&&pba.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(pba.GetString()))CheckAsset(packageDir,pba.GetString()!,$"Phase {name} BackgroundAudio",e);float phaseDurDefault=Number(phase,"SignalDurationSec",defaultDur);if(!phase.TryGetProperty("Signals",out var signals)||signals.ValueKind!=JsonValueKind.Array||signals.GetArrayLength()==0){e.Add($"Phase '{name}' must contain at least one signal.");continue;}float phaseEnd=0;foreach(var si in signals.EnumerateArray()){if(!Text(si,"Signal",out var st)){e.Add($"Phase '{name}' has a signal without Signal name.");continue;}if(!available.Contains(st))e.Add($"Phase '{name}' references undefined signal '{st}'.");float appear=Number(si,"AppearSec",-1);if(appear<0)e.Add($"Phase '{name}' signal '{st}' requires non-negative AppearSec.");float dur=Number(si,"DurationSec",phaseDurDefault);if(dur<=0)e.Add($"Phase '{name}' signal '{st}' duration must be > 0.");phaseEnd=Math.Max(phaseEnd,appear+dur);float bearing=Number(si,"Bearing",-1);if(bearing<0||bearing>360)e.Add($"Phase '{name}' signal '{st}' Bearing must be 0..360.");if(si.TryGetProperty("AudioFile",out var ia)&&ia.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(ia.GetString()))CheckAsset(packageDir,ia.GetString()!,$"Phase {name} signal {st} AudioFile",e);}
   if(phase.TryGetProperty("Alerts",out var alerts)&&alerts.ValueKind==JsonValueKind.Array)foreach(var a in alerts.EnumerateArray()){float at=Number(a,"AppearSec",-1);if(at<0)e.Add($"Phase '{name}' alert requires non-negative AppearSec.");else if(at>phaseEnd)e.Add($"Phase '{name}' alert at {at}s occurs after computed phase end {phaseEnd}s.");}
  }
  return e;
 }
 static bool Text(JsonElement x,string n,out string v){v="";if(!x.TryGetProperty(n,out var p)||p.ValueKind!=JsonValueKind.String||string.IsNullOrWhiteSpace(p.GetString()))return false;v=p.GetString()!;return true;}
 static float Number(JsonElement x,string n,float d){if(x.TryGetProperty(n,out var p)&&p.ValueKind==JsonValueKind.Number&&p.TryGetSingle(out var f))return f;return d;}
 static void CheckAsset(string root,string rel,string label,List<string> e){try{if(Uri.TryCreate(rel,UriKind.Absolute,out _)){e.Add(label+" must be a package-relative path.");return;}var full=Path.GetFullPath(Path.Combine(root,rel));if(!full.StartsWith(Path.GetFullPath(root)+Path.DirectorySeparatorChar,StringComparison.Ordinal)){e.Add(label+" escapes the package directory.");return;}if(!File.Exists(full))e.Add(label+" references missing file '"+rel+"'.");}catch{e.Add(label+" contains an invalid path.");}}
}
static class Db {
 static SqliteConnection C(string f)=>new($"Data Source={f}");
 public static async Task Init(string f){await using var c=C(f);await c.OpenAsync();var q=c.CreateCommand();q.CommandText="""CREATE TABLE IF NOT EXISTS runs(run_id TEXT PRIMARY KEY,subject_id TEXT,experiment_package TEXT,started_utc TEXT,ended_utc TEXT,status TEXT,csv_file TEXT,meta_file TEXT,heartbeat_utc TEXT);CREATE TABLE IF NOT EXISTS event_sequences(run_id TEXT,seq INTEGER,PRIMARY KEY(run_id,seq));CREATE INDEX IF NOT EXISTS ix_runs_subject_exp ON runs(subject_id,experiment_package,status);""";await q.ExecuteNonQueryAsync();}
 public static async Task Start(string f,RunMetadata m,string csv,string meta){await using var c=C(f);await c.OpenAsync();var q=c.CreateCommand();q.CommandText="INSERT INTO runs VALUES($r,$s,$e,$st,'','ACTIVE',$c,$m,$h)";q.Parameters.AddWithValue("$r",m.RunId);q.Parameters.AddWithValue("$s",m.SubjectId);q.Parameters.AddWithValue("$e",m.ExperimentPackage);q.Parameters.AddWithValue("$st",m.StartedUtc);q.Parameters.AddWithValue("$c",csv);q.Parameters.AddWithValue("$m",meta);q.Parameters.AddWithValue("$h",DateTime.UtcNow.ToString("O"));await q.ExecuteNonQueryAsync();}
 public static async Task Heartbeat(string f,string r){await using var c=C(f);await c.OpenAsync();var q=c.CreateCommand();q.CommandText="UPDATE runs SET heartbeat_utc=$h WHERE run_id=$r AND status='ACTIVE'";q.Parameters.AddWithValue("$h",DateTime.UtcNow.ToString("O"));q.Parameters.AddWithValue("$r",r);await q.ExecuteNonQueryAsync();}
 public static async Task<(string csv,string meta)?> GetRun(string f,string r){await using var c=C(f);await c.OpenAsync();var q=c.CreateCommand();q.CommandText="SELECT csv_file,meta_file FROM runs WHERE run_id=$r";q.Parameters.AddWithValue("$r",r);await using var rd=await q.ExecuteReaderAsync();return await rd.ReadAsync()?(rd.GetString(0),rd.GetString(1)):null;}
 public static async Task<bool> HasCompleted(string f,string s,string e){await using var c=C(f);await c.OpenAsync();var q=c.CreateCommand();q.CommandText="SELECT 1 FROM runs WHERE subject_id=$s AND experiment_package=$e AND status='COMPLETED' LIMIT 1";q.Parameters.AddWithValue("$s",s);q.Parameters.AddWithValue("$e",e);return await q.ExecuteScalarAsync()!=null;}
 public static async Task Finish(string f,string r,bool complete,string reason,string ended){await using var c=C(f);await c.OpenAsync();var q=c.CreateCommand();q.CommandText="UPDATE runs SET status=$s,ended_utc=$e,heartbeat_utc=$e WHERE run_id=$r";q.Parameters.AddWithValue("$s",complete?"COMPLETED":"ABORTED");q.Parameters.AddWithValue("$e",ended);q.Parameters.AddWithValue("$r",r);await q.ExecuteNonQueryAsync();}
 public static async Task<bool> SequenceExists(string f,string r,long n){await using var c=C(f);await c.OpenAsync();var q=c.CreateCommand();q.CommandText="SELECT 1 FROM event_sequences WHERE run_id=$r AND seq=$n";q.Parameters.AddWithValue("$r",r);q.Parameters.AddWithValue("$n",n);return await q.ExecuteScalarAsync()!=null;}
 public static async Task AddSequence(string f,string r,long n){await using var c=C(f);await c.OpenAsync();var q=c.CreateCommand();q.CommandText="INSERT OR IGNORE INTO event_sequences VALUES($r,$n)";q.Parameters.AddWithValue("$r",r);q.Parameters.AddWithValue("$n",n);await q.ExecuteNonQueryAsync();}
 public static async Task<object[]> Results(string f,string filter){await using var c=C(f);await c.OpenAsync();var q=c.CreateCommand();q.CommandText="SELECT csv_file,run_id,subject_id,experiment_package,started_utc,status FROM runs WHERE csv_file LIKE $f ORDER BY started_utc DESC LIMIT 5000";q.Parameters.AddWithValue("$f","%"+filter+"%");var l=new List<object>();await using var r=await q.ExecuteReaderAsync();while(await r.ReadAsync())l.Add(new{fileName=r.GetString(0),runId=r.GetString(1),subjectId=r.GetString(2),experimentPackage=r.GetString(3),startedUtc=r.GetString(4),status=r.GetString(5)});return l.ToArray();}
 public static async Task<List<string>> MarkStale(string f,TimeSpan age){await using var c=C(f);await c.OpenAsync();var cutoff=DateTime.UtcNow.Subtract(age).ToString("O");var list=new List<string>();var q=c.CreateCommand();q.CommandText="SELECT meta_file FROM runs WHERE status='ACTIVE' AND heartbeat_utc < $c";q.Parameters.AddWithValue("$c",cutoff);await using(var r=await q.ExecuteReaderAsync())while(await r.ReadAsync())list.Add(r.GetString(0));var u=c.CreateCommand();u.CommandText="UPDATE runs SET status='ABORTED',ended_utc=$e WHERE status='ACTIVE' AND heartbeat_utc < $c";u.Parameters.AddWithValue("$e",DateTime.UtcNow.ToString("O"));u.Parameters.AddWithValue("$c",cutoff);await u.ExecuteNonQueryAsync();return list;}
}
