using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace SonarTask.UI
{
    /// <summary>One visible editable field with an integrated history dropdown arrow.</summary>
    public sealed class EditableComboBox : MonoBehaviour
    {
        [SerializeField] InputField input;
        [SerializeField] Button arrowButton;
        readonly List<string> options = new();
        GameObject popup;

        public string Text
        {
            get => input ? input.text : string.Empty;
            set { EnsureVisuals(); input.text = value ?? string.Empty; }
        }

        public InputField Input => input;

        public void EnsureVisuals(string placeholder = "")
        {
            if (!input)
            {
                var bg = GetComponent<Image>() ?? gameObject.AddComponent<Image>();
                bg.color = new Color(.12f, .14f, .16f, 1f);
                input = gameObject.GetComponent<InputField>() ?? gameObject.AddComponent<InputField>();
                input.targetGraphic = bg;

                var text = UIFactory.Text("", transform, 18, TextAnchor.MiddleLeft);
                text.gameObject.name = "Text";
                text.rectTransform.offsetMin = new Vector2(10, 3);
                text.rectTransform.offsetMax = new Vector2(-40, -3);
                var ph = UIFactory.Text(placeholder, transform, 18, TextAnchor.MiddleLeft);
                ph.gameObject.name = "Placeholder";
                ph.color = new Color(.7f, .7f, .7f, .8f);
                ph.rectTransform.offsetMin = new Vector2(10, 3);
                ph.rectTransform.offsetMax = new Vector2(-40, -3);
                input.textComponent = text;
                input.placeholder = ph;

                var arrowImage = UIFactory.Panel("HistoryArrow", transform, new Color(.18f, .20f, .23f, 1f));
                var ar = arrowImage.rectTransform;
                ar.anchorMin = new Vector2(1, 0);
                ar.anchorMax = new Vector2(1, 1);
                ar.pivot = new Vector2(1, .5f);
                ar.sizeDelta = new Vector2(36, 0);
                ar.anchoredPosition = Vector2.zero;
                arrowButton = arrowImage.gameObject.AddComponent<Button>();
                arrowButton.targetGraphic = arrowImage;
                UIFactory.DownChevron(arrowImage.transform, Color.white, 15f, 8f, 2.2f);
            }

            // Upgrade scene shells generated by earlier versions that used a Unicode arrow glyph.
            var arrowRoot = transform.Find("HistoryArrow");
            if (arrowRoot) {
                var legacyArrow = arrowRoot.GetComponentInChildren<Text>(true);
                if (legacyArrow && legacyArrow.gameObject.name == "Text") legacyArrow.gameObject.SetActive(false);
                if (!arrowRoot.Find("ChevronDown")) UIFactory.DownChevron(arrowRoot, Color.white, 15f, 8f, 2.2f);
                if (!arrowButton) arrowButton = arrowRoot.GetComponent<Button>();
            }

            arrowButton.onClick.RemoveAllListeners();
            arrowButton.onClick.AddListener(TogglePopup);
        }

        public void SetOptions(IEnumerable<string> values)
        {
            options.Clear();
            if (values != null)
                foreach (var x in values)
                    if (!string.IsNullOrWhiteSpace(x)) options.Add(x);
        }

        void TogglePopup()
        {
            if (popup) { ClosePopup(); return; }
            if (options.Count == 0) return;

            popup = UIFactory.Panel("HistoryPopup", transform, new Color(.055f, .065f, .075f, .995f)).gameObject;
            var pr = (RectTransform)popup.transform;
            pr.anchorMin = new Vector2(0, 0);
            pr.anchorMax = new Vector2(1, 0);
            pr.pivot = new Vector2(.5f, 1);
            pr.anchoredPosition = new Vector2(0, -2);
            float rowHeight = 34;
            pr.sizeDelta = new Vector2(0, Mathf.Min(options.Count, 8) * rowHeight + 8);
            var canvas = popup.AddComponent<Canvas>();
            canvas.overrideSorting = true;
            canvas.sortingOrder = 100;
            popup.AddComponent<GraphicRaycaster>();
            var layout = UIFactory.VLayout(popup.transform, 1, 4);
            layout.childForceExpandHeight = false;

            foreach (var option in options)
            {
                string selected = option;
                var b = UIFactory.Button(option, popup.transform, () => { input.text = selected; ClosePopup(); }, 16);
                UIFactory.Size(b, rowHeight);
                var tx = b.GetComponentInChildren<Text>();
                if (tx)
                {
                    tx.color = Color.white;
                    tx.alignment = TextAnchor.MiddleLeft;
                    tx.rectTransform.offsetMin = new Vector2(10, 2);
                }
            }
        }

        public void ClosePopup()
        {
            if (!popup) return;
            Destroy(popup);
            popup = null;
        }

        void OnDisable() => ClosePopup();
    }
}
