using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace SonarTask.UI
{
    /// <summary>
    /// Small runtime dropdown that uses ordinary Button rows. It avoids platform/theme
    /// differences in Unity's legacy Dropdown template and keeps option text visible.
    /// </summary>
    public sealed class PopupDropdown : MonoBehaviour
    {
        [SerializeField] Text caption;
        [SerializeField] Button openButton;
        [SerializeField] RectTransform popupAnchor;
        readonly List<string> options = new();
        GameObject popup;
        int value;

        public event Action<int> ValueChanged;
        public IReadOnlyList<string> Options => options;
        public int Value => value;
        public void ClearValueChangedListeners() => ValueChanged = null;

        public void EnsureVisuals(string initialText = "Select")
        {
            var bg = GetComponent<Image>() ?? gameObject.AddComponent<Image>();
            bg.color = new Color(.12f, .14f, .16f, 1f);

            if (!caption)
            {
                caption = transform.Find("Caption")?.GetComponent<Text>();
                if (!caption)
                {
                    caption = UIFactory.Text(initialText, transform, 17, TextAnchor.MiddleLeft);
                    caption.gameObject.name = "Caption";
                }
            }
            caption.raycastTarget = false;
            caption.rectTransform.offsetMin = new Vector2(10, 2);
            caption.rectTransform.offsetMax = new Vector2(-34, -2);

            var arrowTransform = transform.Find("ArrowButton");
            Image arrowImage;
            if (!arrowTransform)
            {
                arrowImage = UIFactory.Panel("ArrowButton", transform, new Color(.18f, .20f, .23f, 1f));
                arrowTransform = arrowImage.transform;
                UIFactory.DownChevron(arrowTransform, Color.white, 15f, 8f, 2.2f);
            }
            else
            {
                arrowImage = arrowTransform.GetComponent<Image>() ?? arrowTransform.gameObject.AddComponent<Image>();
                arrowImage.color = new Color(.18f, .20f, .23f, 1f);
                var legacyArrow = arrowTransform.GetComponentInChildren<Text>(true);
                if (legacyArrow) legacyArrow.gameObject.SetActive(false);
                if (!arrowTransform.Find("ChevronDown")) UIFactory.DownChevron(arrowTransform, Color.white, 15f, 8f, 2.2f);
                // Remove/disable the old arrow-only Button if this scene was generated by an earlier version.
                var oldArrowButton = arrowTransform.GetComponent<Button>();
                if (oldArrowButton) oldArrowButton.enabled = false;
            }

            var ar = (RectTransform)arrowTransform;
            ar.anchorMin = new Vector2(1, 0);
            ar.anchorMax = new Vector2(1, 1);
            ar.pivot = new Vector2(1, .5f);
            ar.sizeDelta = new Vector2(34, 0);
            ar.anchoredPosition = Vector2.zero;

            // The root Button covers the entire visible dropdown, including its caption text.
            openButton = GetComponent<Button>() ?? gameObject.AddComponent<Button>();
            openButton.targetGraphic = bg;
            openButton.onClick.RemoveAllListeners();
            openButton.onClick.AddListener(TogglePopup);
            popupAnchor = (RectTransform)transform;
        }

        public void SetOptions(IEnumerable<string> values, int selectedIndex = 0, bool notify = false)
        {
            EnsureVisuals();
            options.Clear();
            if (values != null)
                foreach (var x in values)
                    options.Add(x ?? string.Empty);

            value = options.Count == 0 ? -1 : Mathf.Clamp(selectedIndex, 0, options.Count - 1);
            caption.text = value >= 0 ? options[value] : string.Empty;
            ClosePopup();
            if (notify && value >= 0) ValueChanged?.Invoke(value);
        }

        public void SetValue(int index, bool notify = false)
        {
            if (options.Count == 0) return;
            value = Mathf.Clamp(index, 0, options.Count - 1);
            caption.text = options[value];
            if (notify) ValueChanged?.Invoke(value);
        }

        void TogglePopup()
        {
            if (popup) { ClosePopup(); return; }
            if (options.Count == 0) return;

            popup = UIFactory.Panel("OptionsPopup", transform, new Color(.055f, .065f, .075f, .995f)).gameObject;
            var pr = (RectTransform)popup.transform;
            pr.anchorMin = new Vector2(0, 0);
            pr.anchorMax = new Vector2(1, 0);
            pr.pivot = new Vector2(.5f, 1);
            pr.anchoredPosition = new Vector2(0, -2);
            float rowHeight = 34f;
            pr.sizeDelta = new Vector2(0, Mathf.Min(options.Count, 8) * rowHeight + 8);

            var canvas = popup.AddComponent<Canvas>();
            canvas.overrideSorting = true;
            canvas.sortingOrder = 100;
            popup.AddComponent<GraphicRaycaster>();
            var layout = UIFactory.VLayout(popup.transform, 1, 4);
            layout.childForceExpandHeight = false;

            for (int i = 0; i < options.Count; i++)
            {
                int ix = i;
                var b = UIFactory.Button(options[i], popup.transform, () => Select(ix), 16);
                b.gameObject.name = "Option:" + options[i];
                UIFactory.Size(b, rowHeight);
                var tx = b.GetComponentInChildren<Text>();
                if (tx)
                {
                    tx.color = Color.white;
                    tx.alignment = TextAnchor.MiddleLeft;
                    tx.rectTransform.offsetMin = new Vector2(10, 2);
                }
            }
        }

        void Select(int index)
        {
            value = index;
            caption.text = options[index];
            ClosePopup();
            ValueChanged?.Invoke(index);
        }

        public void ClosePopup()
        {
            if (!popup) return;
            Destroy(popup);
            popup = null;
        }

        void OnDisable() => ClosePopup();
    }
}
