#if UNITY_EDITOR
using System; using System.IO; using Newtonsoft.Json; using SonarTask.Core; using UnityEditor; using UnityEngine;
namespace SonarTask.EditorTools {
public static class SonarValidationMenu {
 [MenuItem("SONAR/Validate All Experiment Packages")]
 public static void ValidateAll(){var root=Path.GetFullPath("Experiments");if(!Directory.Exists(root)){Debug.LogWarning("Experiments directory not found: "+root);return;}int good=0,bad=0;foreach(var dir in Directory.GetDirectories(root)){var json=Path.Combine(dir,"experiment.json");if(!File.Exists(json))continue;try{var raw=File.ReadAllText(json);var d=JsonConvert.DeserializeObject<ExperimentDefinition>(raw);var errors=ExperimentValidator.Validate(d);ValidateAssets(d,dir,errors);if(errors.Count>0){bad++;Debug.LogError(Path.GetFileName(dir)+":\n - "+string.Join("\n - ",errors));continue;}var r=ExperimentResolver.Resolve(d);good++;Debug.Log($"{Path.GetFileName(dir)} valid. {r.Phases.Count} phase(s): "+string.Join(", ",r.Phases.ConvertAll(p=>$"{p.Name}={p.DurationSec:0.###}s")));}catch(Exception e){bad++;Debug.LogError(Path.GetFileName(dir)+": "+e);}}Debug.Log($"SONAR experiment validation finished: {good} valid, {bad} invalid.");}
 static void ValidateAssets(ExperimentDefinition d,string root,System.Collections.Generic.List<string> e){Check(root,d.InstructionsFile,"InstructionsFile",e);Check(root,d.ExperimentSettings.BackgroundAudio,"BackgroundAudio",e);foreach(var kv in d.ExperimentSettings.SignalDefinitions)Check(root,kv.Value.AudioFile,$"SignalDefinitions.{kv.Key}.AudioFile",e);foreach(var pk in d.Phases){var p=pk.Value;Check(root,p.BackgroundAudio,$"Phase {pk.Key} BackgroundAudio",e);foreach(var s in p.SignalDefinitions)Check(root,s.AudioFile,$"Phase {pk.Key} SignalDefinition {s.Name} AudioFile",e);foreach(var s in p.Signals)Check(root,s.AudioFile,$"Phase {pk.Key} Signal {s.Signal} AudioFile",e);}}
 static void Check(string root,string rel,string label,System.Collections.Generic.List<string> e){if(string.IsNullOrWhiteSpace(rel))return;try{if(Uri.TryCreate(rel,UriKind.Absolute,out _)){e.Add(label+" must be package-relative.");return;}var rr=Path.GetFullPath(root);var f=Path.GetFullPath(Path.Combine(rr,rel));if(!f.StartsWith(rr+Path.DirectorySeparatorChar,StringComparison.Ordinal)){e.Add(label+" escapes the package directory.");return;}if(!File.Exists(f))e.Add(label+" references missing file '"+rel+"'.");}catch{e.Add(label+" contains an invalid path.");}}
 [MenuItem("SONAR/Determinism Smoke Test")]
 public static void Determinism(){const long seed=90210617;double a=DeterministicNoise.Smooth(seed,1,"SIG-0042",2,12345,7,31),b=DeterministicNoise.Smooth(seed,1,"SIG-0042",2,12345,7,31);if(BitConverter.DoubleToInt64Bits(a)!=BitConverter.DoubleToInt64Bits(b))throw new Exception("DeterministicNoise failed repeatability smoke test.");Debug.Log("Determinism smoke test passed: "+a.ToString("R"));}
}
}
#endif
